export const BUILT_IN_PROVIDER_DISPLAY_NAMES: Record<string, string> = {
	anthropic: "Anthropic",
	"amazon-bedrock": "亚马逊 Bedrock",
	"azure-openai-responses": "Azure OpenAI 响应",
	cerebras: "Cerebras",
	"cloudflare-ai-gateway": "Cloudflare AI 网关",
	"cloudflare-workers-ai": "Cloudflare Workers AI",
	deepseek: "DeepSeek",
	fireworks: "Fireworks",
	google: "谷歌 Gemini",
	"google-vertex": "谷歌 Vertex AI",
	groq: "Groq",
	huggingface: "Hugging Face",
	"kimi-coding": "Kimi 编程",
	mistral: "Mistral",
	minimax: "MiniMax",
	"minimax-cn": "MiniMax (中国)",
	moonshotai: "Moonshot AI",
	"moonshotai-cn": "Moonshot AI (中国)",
	opencode: "OpenCode Zen",
	"opencode-go": "OpenCode Go",
	openai: "OpenAI",
	openrouter: "OpenRouter",
	together: "Together AI",
	"vercel-ai-gateway": "Vercel AI 网关",
	xai: "xAI",
	zai: "ZAI",
	poe: "Poe",
	xiaomi: "小米 MiMo",
	"xiaomi-token-plan-cn": "小米 MiMo Token 计划 (中国)",
	"xiaomi-token-plan-ams": "小米 MiMo Token 计划 (阿姆斯特丹)",
	"xiaomi-token-plan-sgp": "小米 MiMo Token 计划 (新加坡)",
};
